spring.datasource.url=jdbc:sqlserver://employee-db-server1.database.windows.net:1433;database=employee-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

spring.datasource.username=${sql-username}
spring.datasource.password=${sql-password}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
